name: phone_ide
description: PhoneIDE is a highly dynamic IDE for learning on freeCodeCamp's mobile app.
version: 2.0.0
repository: https://github.com/freeCodeCamp/PhoneIDE
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  flutter_inappwebview: ^6.1.5
  flutter_js: ^0.8.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lints: ^2.1.1
flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  assets:
    - assets/highlighter/
